using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RobotMoveScript : MonoBehaviour
{
    [SerializeField, Header("ƒGƒlƒ‹ƒMپ[ٹا—‌ƒXƒNƒٹƒvƒg")]
    EnergyScript energyScript;

    //ƒچƒ{ƒbƒg‚جRigidbody
    Rigidbody robotRB;
    [SerializeField, Header("ƒچƒ{ƒbƒg‚ج–§“x")]
    float density = 1.0f;
    [SerializeField,Header("ˆع“®—ح")]
    float force = 1.0f;

    void Start()
    {
        robotRB = GetComponent<Rigidbody>();

        //ƒچƒ{ƒbƒg‚جژ؟—ت‚ًŒvژZ
        robotRB.mass = transform.localScale.x * transform.localScale.y * transform.localScale.z * density;
    }

    void Update()
    {
        //ƒeƒXƒg—p
        if (Input.GetKeyDown(KeyCode.A)) MoveLeft();
        if (Input.GetKeyDown(KeyCode.D)) MoveRight();
        if (Input.GetKeyDown(KeyCode.W)) MoveFront();                 
        if (Input.GetKeyDown(KeyCode.S)) MoveBack();
        if (Input.GetKeyDown(KeyCode.UpArrow)) MoveUp();
        if (Input.GetKeyDown(KeyCode.DownArrow)) MoveDown();
    }

    public void MoveLeft()//چ¶ˆع“®
    {
        if (energyScript.UseEnergy(0.5f))
        {
            robotRB.AddForce(-transform.right * force / robotRB.mass, ForceMode.Impulse);
        }
    }
    public void MoveRight()//‰Eˆع“®
    {
        if (energyScript.UseEnergy(0.5f))
        {
            robotRB.AddForce(transform.right * force / robotRB.mass, ForceMode.Impulse);
        }
    }
    public void MoveFront()//‘O•ûˆع“®
    {
        if (energyScript.UseEnergy(0.5f))
        {
            robotRB.AddForce(transform.forward * force / robotRB.mass, ForceMode.Impulse);
        }
    }
    public void MoveBack()//Œم•ûˆع“®
    {
        if (energyScript.UseEnergy(0.5f))
        {
            robotRB.AddForce(-transform.forward * force / robotRB.mass, ForceMode.Impulse);
        }
    }
    public void MoveUp()//ڈمˆع“®
    {
        if (energyScript.UseEnergy(0.5f))
        {
            robotRB.AddForce(transform.up * force / robotRB.mass, ForceMode.Impulse);
        }
    }
    public void MoveDown()//‰؛ˆع“®
    {
        if (energyScript.UseEnergy(0.5f))
        {
            robotRB.AddForce(-transform.up * force / robotRB.mass, ForceMode.Impulse);
        }
    }
}
